mySQL:
  url: "jdbc:mysql://127.0.0.1/GT?user=root&password=&serverTimezone=UTC"
  username: "root"
  password: ""

default-karma: 0
# количество кармы у игрока, который первый раз зашёл

add-karma:
  kill-player: -5
  # при убийстве игрока забирает 5 кармы

add-board-karma: -100
# добавляет игрока на доску, если у него больше -100 кармы

formula: " -1 * %karma% * 10 "

