name: HeadHunterKingdoms
version: '${project.version}'
main: org.gt.headhunterkingdoms.HeadHunterKingdoms
api-version: '1.20'
depend: [Citizens, PlaceholderAPI]
commands:
  karma:
    description: gets Karma
  headBag:
    description: opens HeadBag


permissions:
  hh.headhunterlicense:
    description: license for velocity